"""empty message

Revision ID: 64ec9a0a8787
Revises: 
Create Date: 2024-03-03 16:30:52.443238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ec9a0a8787'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('patronymic', sa.String(length=30), nullable=False),
    sa.Column('passport', sa.String(length=10), nullable=False),
    sa.Column('experience', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_experience'), 'driver', ['experience'], unique=False)
    op.create_index(op.f('ix_driver_first_name'), 'driver', ['first_name'], unique=False)
    op.create_index(op.f('ix_driver_id'), 'driver', ['id'], unique=False)
    op.create_index(op.f('ix_driver_last_name'), 'driver', ['last_name'], unique=False)
    op.create_index(op.f('ix_driver_passport'), 'driver', ['passport'], unique=False)
    op.create_index(op.f('ix_driver_patronymic'), 'driver', ['patronymic'], unique=False)
    op.create_table('user',
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('patronymic', sa.String(length=30), nullable=False),
    sa.Column('group', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_group'), 'user', ['group'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_patronymic'), 'user', ['patronymic'], unique=False)
    op.create_table('trip',
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_departure_time'), 'trip', ['departure_time'], unique=False)
    op.create_index(op.f('ix_trip_id'), 'trip', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_id'), table_name='trip')
    op.drop_index(op.f('ix_trip_departure_time'), table_name='trip')
    op.drop_table('trip')
    op.drop_index(op.f('ix_user_patronymic'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_group'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_driver_patronymic'), table_name='driver')
    op.drop_index(op.f('ix_driver_passport'), table_name='driver')
    op.drop_index(op.f('ix_driver_last_name'), table_name='driver')
    op.drop_index(op.f('ix_driver_id'), table_name='driver')
    op.drop_index(op.f('ix_driver_first_name'), table_name='driver')
    op.drop_index(op.f('ix_driver_experience'), table_name='driver')
    op.drop_table('driver')
    # ### end Alembic commands ###
